### ISSUE TITLE
IT服务系统开发issue

### ISSUE THREAD

**Issue by rpqin** [qinrongjin/blog#2]

**Comment by rpqin** [comment]
hello! my name is qinrongping

**Comment by rpqin** [comment]
![default](https://user-images.githubusercontent.com/22129400/30517472-0478f9b2-9b93-11e7-9c4e-e8e49d5253f1.png)

**Comment by rpqin** [comment]
可以截图

**Comment by rpqin** [comment]
wiki上不能提交word文档吗

**Comment by qinrongjin** [comment]
PDF文件

**Comment by qinrongjin** [comment]
部分  PDF 文件上传，或者工具文件 如redis图形化管理工具 什么的 ，放到文档里面

**Comment by rpqin** [comment]
![default](https://user-images.githubusercontent.com/22129400/30517518-ce4d5610-9b94-11e7-820e-992b85bf671f.png)

**Comment by rpqin** [comment]
在哪个地方提交我的word文档
